# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inclusive Innovation 2030
email: m.leahy@endeva.org
description: > # this means to ignore newlines until "baseurl:"
  ii2030 will bring together innovators from corporates, startups, the public sector, NGOs and science to create solutions for a more inclusive society by 2030.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# External links
registration_page_url: www.example.com
url: s-kennedy.github.io/ii2030

collections:
  tracks:
    output: true


#SASS settings
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
source: src
markdown: kramdown
permalink: pretty
gems:
  - jekyll-feed
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
